"""empty message

Revision ID: fdad31711052
Revises: c546ee1ca169
Create Date: 2023-11-10 14:55:20.320411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import func


# revision identifiers, used by Alembic.
revision = 'fdad31711052'
down_revision = 'c546ee1ca169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charityproject", schema=None) as batch_op:
        batch_op.drop_column("create_date")
        batch_op.add_column(
            sa.Column(
                "create_date",
                sa.DateTime(),
                server_default=func.now(),
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
